try without in script

diff --git a/.github/workflows/Extra-guard.yml b/.github/workflows/Extra-guard.yml
--- a/.github/workflows/Extra-guard.yml
+++ b/.github/workflows/Extra-guard.yml
@@ -33,11 +33,54 @@ jobs:
       - name: Install jq
         run: sudo apt-get install jq
 
-      - name: path
-        run: echo $PATH
 
-      - name: download ruleset
-        run: './.github/customrules/DownloadRules.sh'
+      - name: Download and process ruleset
+        run: |
+          # Controleer of de vereiste omgevingsvariabelen zijn ingesteld
+          if [ -z "$JSON_FILE" ]; then
+            echo "Error: JSON_FILE is not set."
+            exit 1
+          fi
+
+          # Stel de basis-URL in voor de mappings
+          MAPPINGS_URL="https://raw.githubusercontent.com/aws-cloudformation/aws-guard-rules-registry/main/mappings"
+
+          # Stel de basis-URL in voor de regels
+          RULES_URL="https://raw.githubusercontent.com/aws-cloudformation/aws-guard-rules-registry/main/rules/aws"
+
+          # Controleer of de download map bestaat, zo niet, maak deze aan
+          RULES_DIR=".github/customrules/cfn-guard/downloaded_rulesets"
+          mkdir -p "$RULES_DIR"
+
+          # Download het JSON-bestand van de opgegeven URL
+          curl -o "$JSON_FILE" "$MAPPINGS_URL/$JSON_FILE"
+
+          # Controleer of het bestand correct is gedownload
+          if [ ! -s "$JSON_FILE" ]; then
+            echo "Failed to download $JSON_FILE or the file is empty."
+            exit 1
+          fi
+
+          # Verwijder eventuele regels die er nog in stonden zodat de nieuwe enkel getest worden
+          rm -f $RULES_DIR/*
+
+          # Gebruik jq om de regels te extraheren en download de individuele regels
+          jq -r '.mappings[]?.guardFilePath' "$JSON_FILE" | while read -r rule; do
+            rule_url="$RULES_URL/$rule"
+            local_rule_path="$RULES_DIR/$(basename $rule)"
+            echo "Downloading $local_rule_path from $rule_url"
+            curl -s -o "$local_rule_path" "$rule_url"
+            # Controleer of het bestand correct is gedownload
+            if [ ! -s "$local_rule_path" ]; then
+              echo "Failed to download $local_rule_path or the file is empty."
+              exit 1
+            fi
+          done
+
+          echo "All rules downloaded successfully."
+
+      # - name: download ruleset
+      #   run: './.github/customrules/DownloadRules.sh'
 
       - name: Validate ruleset
         uses: aws-cloudformation/cloudformation-guard@action-v0.0.3
